# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox Delta Suite

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/velox_delta_suite.yml'
      - 'pom.xml'
      - 'backends-velox/**'
      - 'gluten-core/**'
      - 'gluten-substrait/**'
      - 'gluten-arrow/**'
      - 'gluten-delta/**'
      - 'gluten-iceberg/**'
      - 'gluten-hudi/**'
      - 'gluten-ut/**'
      - 'package/**'
      - 'shims/**'
      - 'ep/build-velox/**'
      - 'cpp/**'
      - 'dev/**'
      - 'build/mvn'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  MVN_CMD: 'build/mvn -ntp'
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-native-lib-centos-7:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Ccache
        uses: actions/cache/restore@v4
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos7-release-default-${{github.sha}}
          restore-keys: |
            ccache-centos7-release-default
      - name: Build Gluten native libraries
        run: |
          docker run -v $GITHUB_WORKSPACE:/work -w /work apache/gluten:vcpkg-centos-7-gcc13 bash -c "
            set -e
            yum install tzdata -y
            df -a
            cd /work
            export CCACHE_DIR=/work/.ccache
            export CCACHE_MAXSIZE=1G
            mkdir -p /work/.ccache
            ccache -sz
            bash dev/ci-velox-buildstatic-centos-7.sh
            ccache -s
          "
      - name: Save ccache
        if: always()
        uses: actions/cache/save@v4
        id: ccache
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos7-release-default-${{github.sha}}
      - uses: actions/upload-artifact@v4
        with:
          name: velox-native-lib-centos-7-${{github.sha}}
          path: ./cpp/build/
          if-no-files-found: error

  velox-delta-suite-spark35:
    needs: build-native-lib-centos-7
    runs-on: ubuntu-22.04
    env:
      SPARK_TESTING: true
    container: apache/gluten:centos-8-jdk8
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-native-lib-centos-7-${{github.sha}}
          path: ./cpp/build/
      - name: Build and Run VeloxDeltaSuite for Spark 3.5
        run: |
          cd $GITHUB_WORKSPACE/
          export SPARK_SCALA_VERSION=2.12
          yum install -y java-17-openjdk-devel
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          $MVN_CMD clean test -Pspark-3.5 -Pjava-17 -Pbackends-velox -Piceberg -Pdelta -Phudi \
          -Dsuites=org.apache.gluten.execution.VeloxDeltaSuite \
          -DargLine="-Dspark.test.home=/opt/shims/spark35/spark_home/"
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-report
          path: '**/surefire-reports/TEST-*.xml'
      - name: Upload unit tests log files
        if: ${{ !success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-test-log
          path: |
            **/target/*.log
            **/gluten-ut/**/hs_err_*.log
            **/gluten-ut/**/core.*
